name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.300
      - name: Debug Build
        run: dotnet build --configuration=Debug -p:TreatWarningsAsErrors=true Bender.Core
      - name: Release Build
        run: dotnet build --configuration=Release -p:TreatWarningsAsErrors=true Bender.Core
      - name: Tests
        run: dotnet test --configuration=Release ./Bender.Core.Tests
      - name: Set up NuGet
        if: runner.os == 'Windows'
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'
      - name: Create NuGet package
        if: runner.os == 'Windows'
        run: dotnet pack --configuration=Release Bender.Core
      - name: Create Bender Windows CLI
        if: runner.os == 'Windows'
        run: dotnet publish --runtime win-x64 /p:PublishSingleFile=true --configuration=Release Bender -o build_win        
      - name: Upload NuGet package artifact
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v2
        with:
          name: nuget-package
          path: ./bin/release/.*nupkg
      - name: Upload CLI package artifact
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v2
        with:
          name: nuget-package
          path: ./build_win/.*exe          

  publish-nuget:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build-and-test
    runs-on: windows-latest
    steps:
      - name: Download NuGet package artifact
        uses: actions/download-artifact@v2
        with:
          name: nuget-package
      - name: Publish to NuGet
        shell: bash
        run: dotnet nuget push *.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/corytodd/index.json